### ISSUE TITLE
Docs broke a little

### ISSUE THREAD

**Issue by Borketh** [Kyando2/Dizkord.jl#52]
In the documentation, [this line onwards](https://github.com/Humans-of-Julia/Ekztazy.jl/blob/86092f10ac90d9b645e76a7bcb811e1cfcefe1ec/src/utils/helpers.jl#L233) results in a broken markdown escape:
![3B743CDB-3AB4-433A-A003-B826A8D43DF5](https://user-images.githubusercontent.com/80119007/153419444-8e51f261-1923-4289-b0de-468a95a4c730.jpeg)

Also, the docs still says Dizkord.jl everywhere.

**Comment by xxxAnn** [comment]
It still saying Dizkord seems like it's just an old version of the docs. It seems that the split message was already broken in the first place (it's broken in Discord.jl too), I'm not quite sure how to fix it so if anyone has any ideas.

**Comment by Borketh** [comment]
It seems like I was using [the "stable" docs](https://humans-of-julia.github.io/Ekztazy.jl/stable/) instead of [the dev version](https://humans-of-julia.github.io/Ekztazy.jl/dev/). The stable one still has the escaped markdown issue fixed in #53.

**Comment by Borketh** [comment]
Lol yeah it seems "stable" is constantly one commit behind dev, but both are git branch agnostic or something...

**Comment by xxxAnn** [comment]
The "stable" one is based on git tags, here v0.7.0 (latest) is tagged as commit [1ced2f3](https://github.com/Humans-of-Julia/Ekztazy.jl/commit/1ced2f36aaab2f1cd66fef5a72600c264b5bcafc), which is older than #53. It should be fixed on the [stable docs](https://humans-of-julia.github.io/Ekztazy.jl/stable/) as well when a new version is pushed to the Registry and @TagBot updates the tag.
